# The docker compose version
version: "3.9"

# Define the services that will be run in the Docker container
services:
  # Define the Django application service
  app:
    build:
      context: . # Build context is the current directory
      args:
        - DEV=true # Pass an argument to the Dockerfile to indicate development mode
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    volumes:
      - ./app:/app # Mount the app directory to the container so any changes are reflected
    # Command to run the Django development server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # Set the database host to the service name 'db'
      - DB_NAME=recipe_dev_db # Set the database name
      - DB_USER=dev_user # Set the database user
      - DB_PASS=dev_password # Set the database password
    depends_on:
      - db # Ensure the app service starts after the db service
  
  db:
    image: postgres:13-alpine # Use the official Postgres image
    volumes:
      - dev-db-data:/var/lib/postgresql/data # Persist database data
    environment:
      - POSTGRES_DB=recipe_dev_db # Set the database name
      - POSTGRES_USER=dev_user # Set the database user
      - POSTGRES_PASSWORD=dev_password # Set the database password

volumes:
  dev-db-data: 